### ISSUE TITLE
Not working after crDroid 9.0 2022-december update

### ISSUE THREAD

**Issue by sanjayahashan** [chenxiaolong/BCR#202]
I used BCR in crDroid 9.0 (android 13) without an issue. But after december update BCR stopped working. Notification Also not present. I tried to get the log by enabling release+debugmode but logs are also not saving. All the permissions are allowed. 
App runs normally. Only the recording is not working.
Device - Redmi Note 8 Pro

**Comment by chenxiaolong** [comment]
Can you check if the recordings and logs are being saved to `Android/data/com.chiller3.bcr/files` in the internal storage? BCR saves the files there if, for some reason, it cannot write to the output directory.

**Comment by sanjayahashan** [comment]
Checked. Folder is empty.

**Comment by chenxiaolong** [comment]
If that's the case, can you grab a logcat after immediately making a call? With adb, you can do that by running `adb logcat -d > logcat.log`. You can also use a logcat app if that's easier.

**Comment by sanjayahashan** [comment]
[logcat.log](https://github.com/chenxiaolong/BCR/files/10311888/logcat.log)

**Comment by chenxiaolong** [comment]
Thanks for the log. I believe this is related to a BCR crash that was fixed in #203 (version 1.27)

```
12-27 12:00:32.936 10657 11033 E AndroidRuntime: Process: com.chiller3.bcr, PID: 10657
12-27 12:00:32.936 10657 11033 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property filename has not been initialized
12-27 12:00:32.936 10657 11033 E AndroidRuntime: 	at com.chiller3.bcr.RecorderThread.run(RecorderThread.kt:597)
```

Could you try again with the latest version of BCR?

**Comment by sanjayahashan** [comment]
> Thanks for the log. I believe this is related to a BCR crash that was fixed in #203 (version 1.27)
> 
> ```
> 12-27 12:00:32.936 10657 11033 E AndroidRuntime: Process: com.chiller3.bcr, PID: 10657
> 12-27 12:00:32.936 10657 11033 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property filename has not been initialized
> 12-27 12:00:32.936 10657 11033 E AndroidRuntime: 	at com.chiller3.bcr.RecorderThread.run(RecorderThread.kt:597)
> ```
> 
> Could you try again with the latest version of BCR?
[logcat.log](https://github.com/chenxiaolong/BCR/files/10312015/logcat.log)

Tried updating. But still don't work. Attached the new ADB log here.

**Comment by chenxiaolong** [comment]
Thanks for the new logs. This might be a bug in the ROM. Android never reports that the call is `ACTIVE`, so BCR didn't begin recording. Android is reporting that the call went straight from `DIALING` to `DISCONNECTING`.

```
12-28 09:21:33.695  9613  9613 D RecorderInCallService: handleStateChange: Call [id: TC@2, state: DIALING, details: [id: TC@2, state: DIALING, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 1, UserHandle{0}, hdl: tel:****, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE], props: [Properties:]]], null, 1

...

12-28 09:21:44.960  9613  9613 D RecorderInCallService: onStateChanged: Call [id: TC@2, state: DISCONNECTING, details: [id: TC@2, state: DISCONNECTING, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, 1, UserHandle{0}, hdl: tel:****, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE], props: [Properties:]]], 10
```

**Comment by sanjayahashan** [comment]
Thanks for the clarification @chenxiaolong. I tried using Call Recorder - SKVALEX since BCR failed. It's working fine though. 
🥲

**Comment by chenxiaolong** [comment]
I believe that app (and probably most others) use a completely different mechanism for detecting calls (the `ACTION_PHONE_STATE_CHANGED` method).

BCR uses the same method that things like Android Auto and smartwatches detect calls (`InCallService`). If `InCallService` is buggy in the ROM, BCR won't work. Unfortunately, it's not feasible to add other detection methods to BCR.

**Comment by sanjayahashan** [comment]
This isssue is resolved somehow. I have no idea how. Recorder is working fine.
