### ISSUE TITLE
app icon

### ISSUE THREAD

**Issue by TeaqariaWTF** [chenxiaolong/BCR#451]
The application icon looks different when installed with KernelSU.

Android : 13 
Ksu app : v.0.7.0
BCR : 1.54
![Screenshot_20231025-214824](https://github.com/chenxiaolong/BCR/assets/90970076/a1f499e6-c783-474e-96db-3b4e71b941d1)

![Screenshot_20231025-215129_Paranoid_Launcher](https://github.com/chenxiaolong/BCR/assets/90970076/5e9448df-33b5-4c20-88de-207fab4b238b)

**Comment by chenxiaolong** [comment]
Hmm, do you have any special KernelSU configuration? Usually, this happens if root access is hidden for some system components, making them unable to read BCR's APK.

**Comment by TeaqariaWTF** [comment]
I think it's a problem with kernel su, I gave root access via the kernel su app and the problem was solved

**Comment by chenxiaolong** [comment]
Great, thanks for reporting back.

**Comment by Rtizer-9** [comment]
@chenxiaolong @TeaqariaWTF I'm having the same issue but it doesn't resolve itself as mentioned by giving root permission in ksu.

The storage folder is full of crash logs. When I reflash the module it will work sometimes and then crash.

I disabled shamiko and now recording works (I've not rebooted again) but the app icon remains the same just like shown in the above screenshot.

I understand that because of the complex nature of how ksu/magisk grant system permission to apps and how shamiko/Zygisk/riru can interfere with permission by whitelisting/blacklisting it would be better if you can list the things which need unrestricted system permission for bcr to work perfectly.

I would be happy to give an app like bcr as much unrestricted access to the system as possible but at the moment it's having issues even after giving root access in ksu.

**Comment by chenxiaolong** [comment]
I think the main problem here is that it's not BCR that needs access to the system, but that the system needs access to BCR. Specifically, the `.apk` must be visible to the system components that deal with apps (like `system_server`). BCR doesn't need any root permissions itself. The module is only used to install the apk into `/system/priv-app/` because system apps are allowed to record calls. Due to that, I'm not surprised that giving root access to BCR doesn't really make a difference.

I don't personally use KernelSU, so I'm not sure what exact configuration changes are needed to make things work properly. Shamiko also isn't open source, so I'm not sure what additional things it affects either (though several people have reported issues with it breaking BCR in the past).

**Comment by TeaqariaWTF** [comment]
The source of the problem is shamiko, if bcr is installed after shamiko this error occurs.

A reminder can be added for this, always bcr should be loaded before shamiko

**Comment by Rtizer-9** [comment]
@TeaqariaWTF  thanks it worked, my shamiko is disabled and an update was already there (1.55) which I did leading to installing bcr when no shamiko is present and after reboot the icon is back to normal.

**Comment by Klusio19** [comment]
I have the same problem when using Kitsune Mask with "Enforce SuList". The icon is missing from the launcher, and full package name is displayed instead od "BCR"

**Comment by TeaqariaWTF** [comment]
> Kitsune Mask'i "Enforce SuList" ile kullanırken de aynı sorunu yaşıyorum. Başlatıcıda simge yok ve "BCR" yerine tam paket adı görüntüleniyor

Install the APK file from the zip file

**Comment by Rtizer-9** [comment]
@TeaqariaWTF If I've bcr installed now and working perfectly and now if I enable shamiko would it be the right order to do?

**Comment by TeaqariaWTF** [comment]
> @TeaqariaWTFŞimdi bcr'yi kurduysam ve mükemmel çalışıyorsam ve şimdi shamiko'yu etkinleştirirsem bu doğru bir sıralama olur mu?

Yes, it should work this way
